name: Trigger model training
on: [push]

jobs:
  start_training:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install kaggle
          kaggle kernels push -p ./kaggle_kernel/
