on:
  workflow_dispatch:
jobs:
  get_new_model:
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
    steps:
      - uses: actions/checkout@v3 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
      - name: Install dependencies
        run: pip install wandb
      - name: Login to W&B
        run: wandb login
      - name: Fetch Artifact
        run: python fetch_model_wb.py
      - name: Commit model
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "artifacts"
          git diff-index --quiet HEAD || (git commit -a -m "updated files" --allow-empty)
      - name: Push model
        uses: actions/checkout@v3 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
        
      
        
    
  
